/**
 * Export the shared unit/weapon catalog (src/oob/shared-catalog.ts) as JSON
 * and as a generated ES module for the sister wargame-map project
 * (interactive/wargame-map), which treats Battlecmo's catalog as its single
 * source of truth for weapons/airframes/sensors.
 *
 * Unlike tools/bake-terrain.mjs (a one-time network fetch run with plain
 * node), this script imports the project's own TypeScript source, so it's
 * run through tsx (already present in this environment's npx cache; add it
 * to devDependencies if that ever stops being true):
 *
 *   npx tsx tools/export-catalog.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SHARED_CATALOG } from '../src/oob/shared-catalog';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const WARGAME_MAP_ROOT = resolve(REPO_ROOT, '../../interactive/wargame-map');

const generated = new Date().toISOString();

const jsonOut = resolve(REPO_ROOT, 'tools/catalog.json');
writeFileSync(jsonOut, JSON.stringify({ meta: { source: 'icomppower/Battlecmo', generated }, ...SHARED_CATALOG }, null, 2) + '\n');
console.log(`wrote ${jsonOut}`);

const esmBody = `/* GENERATED by battlecmo tools/export-catalog.ts — do not hand-edit.
 * Single source of truth: icomppower/Battlecmo catalog. Regenerate there. */
export const CATALOG = ${JSON.stringify(
  {
    meta: { source: 'icomppower/Battlecmo', generated },
    weapons: SHARED_CATALOG.weapons,
    airframes: SHARED_CATALOG.airframes,
    sensors: SHARED_CATALOG.sensors,
  },
  null,
  2,
)};
`;

const wargameMapJsDir = resolve(WARGAME_MAP_ROOT, 'js');
mkdirSync(wargameMapJsDir, { recursive: true });
const esmOut = resolve(wargameMapJsDir, 'catalog.js');
writeFileSync(esmOut, esmBody);
console.log(`wrote ${esmOut}`);

console.log(
  `catalog: ${Object.keys(SHARED_CATALOG.weapons).length} weapons, ` +
    `${Object.keys(SHARED_CATALOG.airframes).length} airframes, ` +
    `${Object.keys(SHARED_CATALOG.sensors).length} sensors`,
);
